// File: src/Elements/Sections/Heros/defaultHeroStyles.js

export const defaultHeroStyles = {
  heroSection: {
    display: 'flex',
    position: 'relative',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    backgroundColor: '#ffffff',
    gap: '1rem',
    margin: '0',
  },
  heroContent: {
    flex: '1',
    minWidth: '300px',
    maxWidth: '600px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1rem',
  },
  heroRightContent: {
    backgroundColor: '#ffffff',
  },
  heroLeftContent: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  heroTitle: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    marginBottom: '16px',
  },
  heroDescription: {
    fontSize: '1rem',
    lineHeight: '1.5',
    marginBottom: '24px',
  },
  buttonContainer: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    justifyContent: 'center',
  },
  primaryButton: {
    backgroundColor: '#334155',
    color: '#ffffff',
    padding: '12px 24px',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
    fontSize: '1rem',
    '&:hover': {
      backgroundColor: '#1e293b',
      transform: 'translateY(-1px)',
    },
  },
  heroImageContainer: {
    flex: '1',
    minWidth: '300px',
    maxWidth: '600px',
    textAlign: 'center',
    marginTop: '20px',
  },
  heroImage: {
    maxWidth: '100%',
    height: '400px',
    backgroundColor: '#334155',
    objectFit: 'cover',
    borderRadius: '8px',
  },
};

export const CustomTemplateHeroStyles = {
  heroSection: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: '40px',
    backgroundColor: '#ffffff',
    margin: '0',
    position: 'relative',
    width: '100%',
    boxSizing: 'border-box',
  },
  heroContent: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: '2rem',
    margin: '10px 0',
    position: 'relative',
  },
  caption: {
    fontWeight: 'bold',
    color: '#334155',
    marginBottom: '8px',
    fontSize: '0.875rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  heroTitle: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    marginBottom: '16px',
    color: '#1A1A1A',
    lineHeight: '1.2',
  },
  heroDescription: {
    fontSize: '1rem',
    lineHeight: '1.5',
    marginBottom: '24px',
    color: '#4A4A4A',
  },
  buttonContainer: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    justifyContent: 'flex-start',
    margin: '10px 0',
    padding: '10px',
    position: 'relative',
  },
  primaryButton: {
    backgroundColor: '#334155',
    color: '#ffffff',
    padding: '12px 24px',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
    fontSize: '1rem',
    minWidth: '120px',
    textAlign: 'center',
    display: 'inline-block',
    textDecoration: 'none',
    outline: 'none',
    boxShadow: 'none',
    margin: '0',
    width: 'auto',
    height: 'auto',
    lineHeight: '1.5',
    fontFamily: 'inherit',
    '&:hover': {
      backgroundColor: '#1e293b',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    color: '#334155',
    padding: '12px 24px',
    border: '2px solid #334155',
    fontWeight: 'bold',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
    fontSize: '1rem',
    minWidth: '120px',
    textAlign: 'center',
    display: 'inline-block',
    textDecoration: 'none',
    outline: 'none',
    boxShadow: 'none',
    margin: '0',
    width: 'auto',
    height: 'auto',
    lineHeight: '1.5',
    fontFamily: 'inherit',
    '&:hover': {
      backgroundColor: '#334155',
      color: '#ffffff',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  heroImageContainer: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    textAlign: 'center',
    margin: '10px 0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px',
    position: 'relative',
  },
  heroImage: {
    maxWidth: '100%',
    height: '400px',
    backgroundColor: '#334155',
    objectFit: 'cover',
    borderRadius: '8px',
    border: 'none',
    position: 'relative',
    cursor: 'pointer',
    display: 'inline-flex',
  },
};

export const heroTwoStyles = {
  heroSection: {
    backgroundColor: '#6B7280',
    color: '#fff',
    padding: '60px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: '8px',
    margin: '0',
    position: 'relative',
    width: '100%',
    boxSizing: 'border-box',
  },
  heroContent: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1.5rem',
    width: '100%',
  },
  heroLeftContent: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1.5rem',
    width: '100%',
  },
  heroRightContent: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  heroTitle: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    marginBottom: '16px',
    width: '100%',
    color: '#ffffff',
  },
  heroDescription: {
    fontSize: '1.125rem',
    lineHeight: '1.6',
    marginBottom: '24px',
    width: '100%',
    color: '#ffffff',
  },
  buttonContainer: {
    display: 'flex',
    gap: '12px',
    width: '100%',
    justifyContent: 'center',
    marginTop: '1rem',
  },
  primaryButton: {
    backgroundColor: '#334155',
    color: '#ffffff',
    padding: '12px 24px',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
    fontSize: '1rem',
    minWidth: '120px',
    textAlign: 'center',
    '&:hover': {
      backgroundColor: '#1e293b',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    color: '#ffffff',
    padding: '12px 24px',
    border: '2px solid #ffffff',
    fontWeight: 'bold',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s ease',
    fontSize: '1rem',
    minWidth: '120px',
    textAlign: 'center',
    '&:hover': {
      backgroundColor: '#ffffff',
      color: '#6B7280',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    },
  },
  heroImageContainer: {
    flex: 1,
    minWidth: '300px',
    maxWidth: '600px',
    textAlign: 'center',
    marginTop: '20px',
    width: '100%',
  },
  heroImage: {
    maxWidth: '100%',
    height: '400px',
    backgroundColor: '#334155',
    objectFit: 'cover',
    borderRadius: '8px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
};
