import { defaultNavbarStyles } from "../../Elements/Sections/Navbars/DefaultNavbarStyles";
import { CustomTemplateNavbarStyles } from "../../Elements/Sections/Navbars/DefaultNavbarStyles";
export const typeToTagMap = {
    div: 'div',
    section: 'section',
    h1: 'h1',
    h2: 'h2',
    h3: 'h3',
    p: 'p',
    span: 'span',
    image: 'img',
    video: 'video',
    audio: 'audio',
    iframe: 'iframe',
    navbar: 'nav',
    hero: 'section',
    cta: 'section',
    footer: 'footer',
    button: 'button',
    input: 'input',
    form: 'form',
    ul: 'ul',
    ol: 'ol',
    li: 'li',
    table: 'table',
    tr: 'tr',
    td: 'td',
    anchor: 'a',
    textarea: 'textarea',
    select: 'select',
    option: 'option',
    label: 'label',
    fieldset: 'fieldset',
    legend: 'legend',
    progress: 'progress',
    meter: 'meter',
    blockquote: 'blockquote',
    code: 'code',
    pre: 'pre',
    hr: 'hr',
    caption: 'caption',
    date: 'input',
    twoColumn: 'nav',
    threeColumn: 'nav',
    customTemplate: 'nav',
  };
  
  export const stylesMap = {
    default: defaultNavbarStyles,
    customTemplate: CustomTemplateNavbarStyles,
  };
  