export const SimplefooterStyles = {
  footerSection: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    padding: '2rem 0',
    marginTop: 'auto',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  footerContent: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 1rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    backgroundColor: 'transparent',
  },
  footerText: {
    fontSize: '0.875rem',
    color: '#ffffff',
    textAlign: 'center',
    margin: '0',
    padding: '0',
  },
  footerButton: {
    backgroundColor: '#4D70FF',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#3D60FF',
    },
  },
};

export const DetailedFooterStyles = {
  footerSection: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    padding: '4rem 0',
    marginTop: 'auto',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  footerContent: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 1rem',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '2rem',
    backgroundColor: 'transparent',
  },
  footerTitle: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1rem',
  },
  footerDescription: {
    fontSize: '0.875rem',
    color: '#a0a0a0',
    lineHeight: '1.5',
    marginBottom: '1rem',
  },
  footerText: {
    fontSize: '0.875rem',
    color: '#ffffff',
    margin: '0',
    padding: '0',
  },
  footerLink: {
    color: '#4D70FF',
    textDecoration: 'none',
    fontSize: '0.875rem',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: '#3D60FF',
    },
  },
  footerButton: {
    backgroundColor: '#4D70FF',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#3D60FF',
    },
  },
};

export const TemplateFooterStyles = {
  footerSection: {
    width: '100%',
    backgroundColor: '#1a1a1a',
    color: '#ffffff',
    padding: '3rem 0',
    marginTop: 'auto',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  footerContent: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 1rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1.5rem',
    backgroundColor: 'transparent',
  },
  footerTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  footerDescription: {
    fontSize: '1rem',
    color: '#a0a0a0',
    lineHeight: '1.5',
    marginBottom: '1rem',
    textAlign: 'center',
    maxWidth: '600px',
  },
  footerText: {
    fontSize: '0.875rem',
    color: '#ffffff',
    textAlign: 'center',
    margin: '0',
    padding: '0',
  },
  footerLink: {
    color: '#4D70FF',
    textDecoration: 'none',
    fontSize: '0.875rem',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: '#3D60FF',
    },
  },
  footerButton: {
    backgroundColor: '#4D70FF',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '0.75rem 1.5rem',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#3D60FF',
    },
  },
};

export const DeFiFooterStyles = {
  footerSection: {
    width: '100%',
    backgroundColor: '#0A0A0A',
    color: '#ffffff',
    padding: '3rem 0',
    marginTop: 'auto',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
  },
  footerContent: {
    width: '100%',
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '0 1rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2rem',
    backgroundColor: 'transparent',
  },
  footerLogo: {
    width: '150px',
    height: 'auto',
    marginBottom: '1rem',
  },
  footerTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: '1rem',
    textAlign: 'center',
  },
  footerDescription: {
    fontSize: '1rem',
    color: '#a0a0a0',
    lineHeight: '1.5',
    marginBottom: '1rem',
    textAlign: 'center',
    maxWidth: '600px',
  },
  footerText: {
    fontSize: '0.875rem',
    color: '#ffffff',
    textAlign: 'center',
    margin: '0',
    padding: '0',
  },
  footerLink: {
    color: '#4D70FF',
    textDecoration: 'none',
    fontSize: '0.875rem',
    transition: 'color 0.2s ease',
    '&:hover': {
      color: '#3D60FF',
    },
  },
  footerButton: {
    backgroundColor: '#4D70FF',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '0.75rem 1.5rem',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#3D60FF',
    },
  },
};

